<a href="https://colab.research.google.com/github/bhagyashree-jadhao/numpy_assignments/blob/main/numpy_assigmnents.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install pandas

Defaulting to user installation because normal site-packages is not writeable


# Theoretical Questions:

## 1). Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?


### ans:- Numpy is a  Numerical Python, is a foundational package for scientific computing and data analysis in Python. It provides support for large, multi-dimensional arrays and matrices, along with a vast collection of mathematical functions to operate on these arrays.
### Purpose of NumPy :-
**Efficient Numerical Computation**: NumPy is designed to handle large arrays and matrices of numerical data efficiently. It provides a high-performance, easy-to-use multidimensional array object.

**Mathematical Operations**: It offers a vast collection of mathematical functions to perform operations on arrays, including statistical, algebraic, and trigonometric operations.

**Interoperability**: NumPy arrays are the standard for exchanging data between different libraries for data analysis, such as Pandas, SciPy, and Matplotlib, ensuring seamless integration and interoperability.

**Data Analysis Foundation**: It forms the backbone of many higher-level data analysis libraries like Pandas, which rely on NumPy arrays for efficient data manipulation.
## Advantages
Performance:

**Speed:** NumPy is implemented in C, making array operations significantly faster than those performed using native Python lists.
**Memory Efficiency:** NumPy arrays use contiguous blocks of memory and have a fixed type, leading to more efficient memory usage compared to Python lists.
Convenience:

**Array Operations:** NumPy simplifies many operations through vectorization, which allows operations to be applied element-wise without explicit loops.
Broadcasting: This feature enables arithmetic operations on arrays of different shapes, expanding smaller arrays to larger ones in a flexible manner.
Rich Functions: NumPy includes a wide range of functions for mathematical operations, random sampling, sorting, and more.
Functionality:

**Multi-Dimensional Arrays**: NumPy supports multi-dimensional arrays, which are essential for complex data analysis and scientific computing.
**Linear Algebra and FFT**: It provides comprehensive support for linear algebra operations and Fast Fourier Transform (FFT), crucial for many scientific applications.
Data Manipulation: Features like slicing, indexing, reshaping, and stacking make it easy to manipulate data arrays in various ways.

**Extensive Documentation**: NumPy has thorough documentation and a large, active community that contributes to its development and provides support.
Integration with Other Libraries: NumPy integrates seamlessly with other scientific computing libraries such as SciPy (for advanced mathematical functions), Matplotlib (for plotting), and Pandas (for data manipulation), creating a powerful ecosystem for scientific computing and data analysis.
Enhancements to Python's Capabilities
**Numerical Operations:** NumPy enhances Python's numerical capabilities by providing a robust array object that supports fast and efficient operations, which are otherwise slow and cumbersome with native Python lists.
**Multi-Dimensional Data Handling**: It allows for the handling of multi-dimensional data, which is essential for scientific and engineering applications.
**Broad Scientific Tools**: By offering tools for linear algebra, random sampling, and more, NumPy extends Python's utility in scientific computing.

 NumPy's efficient array handling, rich mathematical functions, and interoperability with other libraries make it indispensable for scientific computing and data analysis. It significantly enhances Python's capabilities by providing performance, convenience, and a strong foundation for more advanced data manipulation and analysis tasks.









### 2). Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

In [ ]:
# 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

## ans
**np.mean()**
Purpose: Computes the arithmetic mean (average) of array elements.
Syntax: np.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)
Usage: Use this function when you need the simple arithmetic mean of an array.
**np.average()**
Purpose: Computes the weighted average of array elements if weights are provided; otherwise, it computes the arithmetic mean.
Syntax: np.average(a, axis=None, weights=None, returned=False)
Usage: Use this function when you need to compute a weighted average.
lets see example

In [ ]:
import numpy as np
data = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(data)
print(mean_value)


3.0


In [ ]:

data = np.array([1, 2, 3, 4, 5])
weights = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
weighted_avg = np.average(data, weights=weights)
print(weighted_avg)


3.6666666666666665


### 3) . Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.


## ans

Reversing a NumPy array along different axes can be achieved using slicing and specific NumPy functions. Here are the methods for reversing arrays and examples for both 1D and 2D arrays.

In [ ]:
#Reversing a 1D Array
#To reverse a 1D array, you can use slicing with a step of -1.

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
reversed_arr


array([5, 4, 3, 2, 1])

In [ ]:
# Reversing a 2D Array
# To reverse a 2D array, you can reverse along different axes:

#Reversing Along Axis 0 (Rows)

# 2D Array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_2d_axis0 = arr_2d[::-1, :]

print("Original 2D Array:")
print(arr_2d)
print("Reversed 2D Array along Axis 0:")
print(reversed_2d_axis0)


Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed 2D Array along Axis 0:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
#  Reversing Along Axis 1 (Columns)
reversed_2d_axis1 = arr_2d[:, ::-1]

print("Reversed 2D Array along Axis 1:")
reversed_2d_axis1


Reversed 2D Array along Axis 1:


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [ ]:
#Reversing Along Both Axes

reversed_2d_both_axes = arr_2d[::-1, ::-1]

print("Reversed 2D Array along Both Axes:")
reversed_2d_both_axes


Reversed 2D Array along Both Axes:


array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
#Using np.flip()
#NumPy also provides the np.flip() function, which can be used to reverse an array along any axis.

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = np.flip(arr)
reversed_arr

array([5, 4, 3, 2, 1])

In [ ]:
# 2D Array Along Axis 0
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_2d_axis0 = np.flip(arr_2d, axis=0)
print(arr_2d)
reversed_2d_axis0

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
#2D Array Along Axis 1
reversed_2d_axis1 = np.flip(arr_2d, axis=1)
reversed_2d_axis1


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [ ]:
# 2D Array Along Both Axes
reversed_2d_both_axes = np.flip(arr_2d)
reversed_2d_both_axes

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
## ans
Reversing a NumPy array along different axes can be achieved using slicing and specific NumPy functions. Here are the methods for reversing arrays and examples for both 1D and 2D arrays.

###  4). How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

ans:- ans:- in numpy array differnt data type occupy differnt amount of memory .of element determine by dtype attribute.
data type are int integer int32 take 4 bytes of memory int64 take 8 bytes.and flaot (flaot 64) and float32.
Using the correct data type ensures that the precision of the calculations is maintained. For example, if you are dealing with floating-point numbers, using float32 vs. float64 affects the precision of calculations.
Operations on arrays are faster when using smaller data types. For instance, performing computations on int8 arrays is faster than on int64 arrays because smaller data types require less memory bandwidth and CPU processing.


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr.dtype)
arr1=np.array([1.1,2.1,3.1,4.1,5.1])
print(arr1.dtype)

int64
float64


### 5). Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

#ans:-
  In NumPy, ndarrays (N-dimensional arrays) are a central data structure used to store elements of the same data type in a grid-like structure. The "n-dimensional" aspect means they can represent data in various dimensions, such as 1D, 2D, 3D, and so on, making them highly flexible for numerical computations.
Key Features of NumPy ndarrays:
Homogeneous: All elements in an ndarray must be of the same data type, which makes it more efficient for numerical operations.
Multi-dimensional: Supports multiple dimensions (1D, 2D, 3D, etc.), making them suitable for complex data manipulations like matrices, tensors, etc.
Efficient Memory Usage: Arrays are stored in contiguous blocks of memory, ensuring faster access to elements compared to Python lists.
Vectorized Operations: Operations on ndarrays are vectorized, meaning you can apply operations element-wise without explicit loops. This is faster than using loops with standard Python lists.
Broadcasting: NumPy supports broadcasting, which allows operations between arrays of different shapes by automatically expanding the smaller array to match the shape of the larger one.
Advanced Indexing and Slicing: ndarrays provide more advanced indexing techniques than Python lists, supporting multi-dimensional slicing, boolean indexing, and fancy indexing.
Operations can be performed in-place, saving memory.
## differnce from list and ndarray as follows
numpy ndaray is Homogeneous (all elements are the same type)	python list is Heterogeneous (elements can have different types).
in numpy ndaray Stored in contiguous memory blocks, highly memory-efficient	list is Less efficient, elements are pointers to objects, scattered in memory
in numpy ndarray Faster for numerical operations due to vectorization	.
list is Slower as operations involve Python loops.
numpy ndaaray is Supports multiple dimensions.
list is  (n-dimensional)	Typically 1D, but can nest lists for multi-dimensionality, which is inefficient.
Mathematical Operations in numpy array	Supports element-wise operations, matrix multiplication, broadcasting, etc.	in list Requires manual loops for element-wise operations.
array has Fixed size once created, but can create new arrays with modified size	list is Flexible size, elements can be appended or removed easily.
in numpy array Rich set of mathematical, statistical, and algebraic functions.	in list a Limited built-in functions for lists; additional operations require manual implementation.


### 6). Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
ans 1. Memory Efficiency
Python Lists: Lists are arrays of pointers to objects in memory. Each element in a list is a reference to a Python object, which incurs overhead in terms of memory and CPU time when accessing elements. Additionally, lists can store heterogeneous data types, further increasing memory usage due to metadata (type and reference).
NumPy Arrays: NumPy stores data in contiguous memory blocks with fixed data types (homogeneous), making it much more memory-efficient. Because of this, NumPy arrays are more compact in memory, especially for large datasets. This leads to faster access and better caching performance.

2. Vectorized Operations
Python Lists: Operations on Python lists often require explicit loops for element-wise operations. For example, multiplying all elements of a list by 2 would require a for-loop to iterate over each element and apply the operation.

NumPy Arrays: NumPy arrays leverage vectorization, which allows applying operations on entire arrays without explicit loops. Operations like addition, multiplication, and broadcasting are performed at the C level, meaning there’s less overhead compared to Python’s looping mechanisms. This can significantly speed up numerical computations, especially for large datasets.
3. Speed
Python Lists: Since Python lists store references to objects, there’s a higher overhead when performing mathematical operations due to type checking and resolving references. This slows down execution for large datasets.

NumPy Arrays: NumPy arrays are implemented in low-level languages (like C and Fortran) and operate directly on the memory buffer, bypassing Python’s object model and type-checking. This gives NumPy a substantial speed advantage, especially for operations on large arrays.

4. Broadcasting
Python Lists: Operations involving different-sized data (like adding a scalar to each element of a list or performing element-wise operations between two lists of different sizes) require manual handling, often involving loops or list comprehensions.

NumPy Arrays: NumPy supports broadcasting, which automatically expands the smaller array to match the size of the larger one during operations. This makes operations like adding a scalar to an array or combining arrays of different shapes very efficient, without the need for explicit loops.

5. Advanced Mathematical Functions
Python Lists: Python lists do not come with built-in support for complex mathematical functions. You would need to use loops or external libraries like math or itertools to perform operations like dot products, trigonometric calculations, etc.

NumPy Arrays: NumPy comes with a wide variety of built-in functions optimized for fast mathematical operations like matrix multiplication, linear algebra functions, statistical calculations, etc. These functions are implemented in optimized C code, offering substantial performance improvements.

For large-scale numerical operations, NumPy arrays offer:

Faster execution due to memory-efficient storage and vectorized operations.
More concise code without needing loops for element-wise operations.
Built-in mathematical operations that are optimized for performance.
Thus, NumPy arrays are generally much faster and more efficient than Python lists for numerical computations.

In [ ]:
my_list = [1, 2, 3, 4, 5]
list_result = [x * 2 for x in my_list]

# NumPy array example (vectorized)
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
arr_result = my_array * 2
print(list_result)
print(arr_result)

[2, 4, 6, 8, 10]
[ 2  4  6  8 10]


In [ ]:
# Python list example
my_list = list(range(10000000))
result = [x * 2 for x in my_list]  # This takes noticeable time.

# NumPy array example
my_array = np.arange(10000000)
arr_result = my_array * 2  # This is much faster.
#print(result)
print(arr_result)


Buffered data was truncated after reaching the output size limit.

In [ ]:
# Broadcasting in NumPy
array = np.array([1, 2, 3])
scalar = 5
result = array + scalar  # NumPy automatically adds 5 to each element.



### 7.Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
ans:- In NumPy, vstack() and hstack() are functions used to stack arrays vertically and horizontally, respectively.
vstack() Function: Vertical Stacking
Purpose: Stacks arrays vertically (row-wise), i.e., along axis 0.
Behavior: Combines arrays by stacking them on top of one another.
Array Shape Requirement: The arrays must have the same number of columns (i.e., the same second dimension if 2D).
hstack() Function: Horizontal Stacking
Purpose: Stacks arrays horizontally (column-wise), i.e., along axis 1.
Behavior: Combines arrays by stacking them side by side.
Array Shape Requirement: The arrays must have the same number of rows (i.e., the same first dimension if 2D).
Use vstack() to stack arrays on top of each other (vertically).
Use hstack() to stack arrays side by side (horizontally).
These functions are particularly useful when combining arrays in multi-dimensional contexts, such as matrix concatenation in machine learning and data analysis.








In [ ]:
import numpy as np

# Define two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vertical stack
result_vstack = np.vstack((arr1, arr2))
print("Vertical Stack:\n", result_vstack)


Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [ ]:
arr1_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2_2d = np.array([[7, 8, 9], [10, 11, 12]])

result_vstack_2d = np.vstack((arr1_2d, arr2_2d))
print("Vertical Stack (2D arrays):\n", result_vstack_2d)


Vertical Stack (2D arrays):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Horizontal stack of 1D arrays
result_hstack = np.hstack((arr1, arr2))
print("Horizontal Stack:\n", result_hstack)


Horizontal Stack:
 [1 2 3 4 5 6]


In [ ]:
result_hstack_2d = np.hstack((arr1_2d, arr2_2d))
print("Horizontal Stack (2D arrays):\n", result_hstack_2d)


Horizontal Stack (2D arrays):
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### 8) Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

ans:- In NumPy, the fliplr() and flipud() methods are used to flip arrays along different axes.
fliplr(): Flip Left to Right
Purpose: This function flips the array in the left-right direction, i.e., it reverses the order of columns for a 2D array or the corresponding axis for higher dimensions.
Axis Affected: It flips along the second axis (axis=1) for 2D arrays. For 1D arrays, this method cannot be applied since there is no "left" or "right" in a 1D structure.
flipud(): Flip Up to Down
Purpose: This function flips the array up-down, i.e., it reverses the order of rows for a 2D array or the corresponding axis for higher dimensions.
Axis Affected: It flips along the first axis (axis=0) for 2D arrays. In this case, rows are reversed.
fliplr() is used for flipping an array left-to-right (horizontal flip), affecting the column order in 2D or higher-dimensional arrays.
flipud() is used for flipping an array up-to-down (vertical flip), affecting the row order in 2D or higher-dimensional arrays.
Both functions are useful for array manipulation in tasks involving image processing, data transformation, and matrix operations.

In [ ]:
import numpy as np

# 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Flip the array left to right
result_fliplr = np.fliplr(arr)
print("Original Array:\n", arr)
print("Fliplr Result:\n", result_fliplr)


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Fliplr Result:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
# Flip the array up-down
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result_flipud = np.flipud(arr)
print("Flipud Result:\n", result_flipud)


Flipud Result:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
# 1D Arrays: fliplr() does not work on 1D arrays, whereas flipud() works and simply reverses the elements.
arr_1d = np.array([1, 2, 3, 4])
result_flipud_1d = np.flipud(arr_1d)
print("1D Array flipud Result:", result_flipud_1d)


1D Array flipud Result: [4 3 2 1]


In [ ]:
#3D Arrays:
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])

# Flip 3D array horizontally (left-right)
result_fliplr_3d = np.fliplr(arr_3d)

# Flip 3D array vertically (up-down)
result_flipud_3d = np.flipud(arr_3d)

print("Original 3D Array:\n", arr_3d)
print("Fliplr 3D Result:\n", result_fliplr_3d)
print("Flipud 3D Result:\n", result_flipud_3d)



Original 3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Fliplr 3D Result:
 [[[3 4]
  [1 2]]

 [[7 8]
  [5 6]]]
Flipud 3D Result:
 [[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]


### 9) Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
he array_split() method in NumPy is used to split an array into multiple sub-arrays along a specified axis. It is very similar to the split() method but with one key difference: array_split() can handle uneven splits, meaning it can split an array into sub-arrays of varying sizes when the number of elements isn't evenly divisible by the number of splits.
syntax:- numpy.array_split(array, indices_or_sections, axis=0)
array: The input array to be split.
indices_or_sections: Can be either an integer or a list:
If it is an integer, it specifies the number of equal or nearly equal sub-arrays to split the array into.
If it is a list of integers, it specifies the indices at which to split the array.
axis: The axis along which to split the array. By default, it is axis=0 (row-wise for 2D arrays).
Handling of Uneven Splits:
If the number of elements in the array is not evenly divisible by the number of sections specified, array_split() will distribute the extra elements across the resulting sub-arrays. The sub-arrays at the beginning will have more elements than those at the end.


In [ ]:
#Example 1: Integer as indices_or_sections (uneven split): If the array has 10 elements and you want to split it into 3 sections, array_split() will handle the uneven division by assigning the extra elements to the first few sections.
import numpy as np

# Define a 1D array with 10 elements
arr = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]

# Split the array into 3 sub-arrays
result = np.array_split(arr, 3)

for i, sub_arr in enumerate(result):
    print(f"Sub-array {i+1}: {sub_arr}")
# Here, the original array [0, 1, ..., 9] has been split into 3 sub-arrays. The first sub-array has 4 elements, while the second and third sub-arrays have 3 elements each.


Sub-array 1: [0 1 2 3]
Sub-array 2: [4 5 6]
Sub-array 3: [7 8 9]


In [ ]:
# Example 2: Integer as indices_or_sections (even split):If the number of elements is evenly divisible by the number of splits, the result will be evenly sized sub-arrays.
# Define a 1D array with 12 elements
arr = np.arange(12)  # [0 1 2 3 4 5 6 7 8 9 10 11]

# Split the array into 3 equal parts
result = np.array_split(arr, 3)

for i, sub_arr in enumerate(result):
    print(f"Sub-array {i+1}: {sub_arr}")


Sub-array 1: [0 1 2 3]
Sub-array 2: [4 5 6 7]
Sub-array 3: [ 8  9 10 11]


In [ ]:
# # Example 3: List of indices_or_sections:
#If you provide a list of integers as indices_or_sections, NumPy will split the array at the specified indices. This gives you fine-grained control over how to split the array.
# Define a 1D array
arr = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]

# Split the array at the specified indices [3, 5, 8]
result = np.array_split(arr, [3, 5, 8])

for i, sub_arr in enumerate(result):
    print(f"Sub-array {i+1}: {sub_arr}")


Sub-array 1: [0 1 2]
Sub-array 2: [3 4]
Sub-array 3: [5 6 7]
Sub-array 4: [8 9]


In [ ]:
#Example 4: Splitting 2D Arrays:
#You can also split 2D arrays along a specific axis. By default, array_split() splits row-wise (along axis=0).

# Define a 2D array
arr_2d = np.arange(16).reshape(4, 4)

# Split the 2D array into 3 parts row-wise
result = np.array_split(arr_2d, 3, axis=0)

for i, sub_arr in enumerate(result):
    print(f"Sub-array {i+1}:\n{sub_arr}")

Sub-array 1:
[[0 1 2 3]
 [4 5 6 7]]
Sub-array 2:
[[ 8  9 10 11]]
Sub-array 3:
[[12 13 14 15]]


### 10). Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array oprations.
ans:- 1. Vectorization:
Vectorization refers to the process of applying operations to entire arrays (or vectors) rather than iterating element by element using loops. It allows the use of highly optimized, low-level C or Fortran code to execute operations in parallel, which leads to significant performance improvements over explicit Python loops.

Key Features of Vectorization:
Array-wide operations: Mathematical operations (e.g., addition, multiplication) can be applied directly to entire arrays without needing to write loops.
Performance boost: Since operations are executed at a lower level in compiled code, they are much faster than equivalent Python loops.
Cleaner, more concise code: Code written with vectorized operations is often more readable and easier to maintain.

2. Broadcasting:
Broadcasting in NumPy refers to the ability of the library to perform operations on arrays of different shapes and sizes by "stretching" or "broadcasting" the smaller array to match the shape of the larger array. Broadcasting allows for operations between arrays of different dimensions without making unnecessary copies of data.
Key Features of Broadcasting:
Shape alignment: NumPy automatically aligns arrays with different shapes by "broadcasting" smaller arrays across the larger one.
Memory efficiency: Broadcasting avoids making large copies of arrays, instead reusing memory and performing operations in a way that is memory-efficient.
Dimensionality handling: It simplifies operations between arrays with different dimensionalities by internally matching dimensions where possible.
Broadcasting Rules:
Arrays with different dimensions: NumPy compares the shapes of the arrays from the rightmost dimension, and broadcasting is possible when:
The sizes of the dimensions are equal, or
One of the dimensions has size 1, allowing it to be broadcast to match the size of the other.
Automatic stretching: If a dimension in the smaller array is of size 1, NumPy "stretches" it to match the corresponding dimension of the larger array.
Example 1: Scalar and Array

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Non-vectorized (loop-based) element-wise addition
result = []
for i in range(len(arr1)):
    result.append(arr1[i] + arr2[i])
print(result)


[5, 7, 9]


In [ ]:
# Vectorized element-wise addition
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)
#Performance Benefit: The vectorized code (arr1 + arr2) is faster because it uses highly optimized, parallelized









[5 7 9]


In [ ]:
arr = np.array([1, 2, 3])

# Broadcasting scalar to array
result = arr * 2
print(result)
#Here, the scalar 2 is broadcasted to match the shape of arr, so the multiplication is performed element-wise without needing to explicitly define an array of the same size


[2 4 6]


In [ ]:
# Example 2: Arrays with Different Shapes
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
arr2 = np.array([10, 20, 30])            # Shape: (3,)

# Broadcasting arr2 to match the shape of arr1
result = arr1 + arr2
print(result)

# In this example, arr2 (shape (3,)) is broadcast to match the shape of arr1 (shape (2, 3)). NumPy stretches arr2 along the first axis to perform the element-wise addition.


[[11 22 33]
 [14 25 36]]


In [ ]:
# Broadcasting with Higher Dimensions:

arr1 = np.array([1, 2, 3]).reshape(3, 1)  # Shape: (3, 1)
arr2 = np.array([10, 20, 30])             # Shape: (3,)

result = arr1 + arr2
print(result)
# Here, arr1 (shape (3, 1)) and arr2 (shape (3,)) are broadcast together to result in a final shape of (3, 3).

#Broadcasting and Dimensionality:
#For two arrays to be broadcastable, their dimensions must either be equal or one of them must be 1. Here's an illustration:

#Shape (5, 3) and Shape (1, 3) → Broadcasting works because the first dimension of 1 can be stretched to 5.
#Shape (4, 2, 3) and Shape (2, 3) → Broadcasting works because the second and third dimensions match.
#Shape (3, 3) and Shape (4, 3) → Broadcasting does not work because the first dimensions (3 and 4) do not match.


[[11 21 31]
 [12 22 32]
 [13 23 33]]


# Practical Questions:

### 1). Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.



In [ ]:
import numpy as np


In [ ]:
arr=np.random.randint(1,100,size=(3,3))
arr

array([[21, 95, 92],
       [71, 68, 79],
       [56, 12, 49]])

In [ ]:
#Then, interchange its rows and columns.¶
arr.transpose()

array([[21, 71, 56],
       [95, 68, 12],
       [92, 79, 49]])

In [ ]:
np.transpose(arr)

array([[21, 71, 56],
       [95, 68, 12],
       [92, 79, 49]])

###  2) Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
# Generate a 1D NumPy array with 10 element
one_d_array=np.array(range(1,11))
one_d_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Reshape it into a 2x5 array,
reshape_arr=one_d_array.reshape(2,5)
reshape_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
# then into a 5x2 array.
arr_reshap=reshape_arr.reshape(5,2)
arr_reshap

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### 3). Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:
arr=np.random.rand(4,4)
arr

array([[0.65245283, 0.62904694, 0.44563944, 0.17555139],
       [0.69544416, 0.22047699, 0.85542028, 0.69315685],
       [0.32560999, 0.38046153, 0.27178503, 0.5234138 ],
       [0.97215306, 0.13496661, 0.06181505, 0.77432796]])

In [ ]:
array_6x6=np.zeros((6,6))
array_6x6

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
array_6x6[1:-1, 1:-1] = arr

In [ ]:
print(array_6x6)


[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.65245283 0.62904694 0.44563944 0.17555139 0.        ]
 [0.         0.69544416 0.22047699 0.85542028 0.69315685 0.        ]
 [0.         0.32560999 0.38046153 0.27178503 0.5234138  0.        ]
 [0.         0.97215306 0.13496661 0.06181505 0.77432796 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


### 4). Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
arrs=np.arange(10,60,5)

In [ ]:
arrs

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

###  5). Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations  ( uppercase, lowercase, title case, etc.) to each element.


In [ ]:
str_arr=np.array(['python', 'numpy', 'pandas'])
str_arr

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
str_arr_upper=np.char.upper(str_arr)
str_arr_upper

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [ ]:
str_arr_lower=np.char.lower(str_arr)
str_arr_lower

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
str_arr_title=np.char.title(str_arr)
str_arr_title

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

### 6). Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
char_array=np.array(['python', 'numpy', 'pandas'])
char_array

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
np.char.join(' ', char_array)

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

### 7). Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
arr1=np.arange(1,11).reshape(2,5)
arr2=np.arange(11,21).reshape(2,5)

In [ ]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
arr_add=arr1+arr2
arr_sub=arr1-arr2
arr_mul=arr1*arr2
arr_div=arr2/arr1

In [ ]:
arr_add

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [ ]:
arr_sub

array([[-10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10]])

In [ ]:
arr_mul

array([[ 11,  24,  39,  56,  75],
       [ 96, 119, 144, 171, 200]])

In [ ]:
arr_div

array([[11.        ,  6.        ,  4.33333333,  3.5       ,  3.        ],
       [ 2.66666667,  2.42857143,  2.25      ,  2.11111111,  2.        ]])

### 8) Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
identity_matrix = np.eye(5)

In [ ]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
identity_matrix .diagonal()

array([1., 1., 1., 1., 1.])

In [ ]:
diagonal_elements = np.diag(identity_matrix)
diagonal_elements

array([1., 1., 1., 1., 1.])

### 9) 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [ ]:
arr_1D=np.random.randint(0,1000 ,size=100)

In [ ]:
arr_1D

array([656, 257, 328, 702, 405, 861, 468, 399, 640, 739, 843, 166,  50,
       294, 853,  78, 365, 794, 698, 828, 784, 898,  43, 328, 653, 879,
       256,  89, 353,  87, 233, 888,  83,  63, 679, 225, 918, 430, 820,
       320, 807, 152, 253, 805, 932, 555, 791, 872, 761, 880, 440, 477,
       794, 538, 811, 196, 527, 404, 870, 718, 651, 999, 601, 337, 419,
       884,  81, 528, 835, 326, 962, 750, 438, 875, 508, 963, 554, 541,
       205, 912, 209, 150,  47, 542,  63, 792, 534, 706, 895, 991, 671,
       832, 479, 876, 799, 528, 736,  52, 158, 458])

In [ ]:
for i in arr_1D:
  if i%2==0:
    continue
  else:
    print(i)

257
405
861
399
739
843
853
365
43
653
879
89
353
87
233
83
63
679
225
807
253
805
555
791
761
477
811
527
651
999
601
337
419
81
835
875
963
541
205
209
47
63
895
991
671
479
799


### 10)  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [ ]:
daily_temperatures = np.random.uniform(15, 35, 30)

# Reshape the array into weeks (5 weeks, 6 days each week)
weekly_temperatures = daily_temperatures.reshape(5, 6)

# Calculate the average temperature for each week
weekly_averages = weekly_temperatures.mean(axis=1)

print("Daily Temperatures:\n", daily_temperatures)
print("\nWeekly Temperatures:\n", weekly_temperatures)
print("\nWeekly Averages:\n", weekly_averages)

Daily Temperatures:
 [31.1384336  31.63894677 23.1951493  20.30057231 27.07746834 23.84043317
 20.49688785 23.46218073 31.38813967 19.08680167 22.96201776 26.7947347
 33.15284694 33.35745659 18.8108851  23.7684492  30.90289356 30.73950096
 22.95613832 29.97162939 21.29698085 26.76535791 19.29297512 22.90207893
 25.28275724 17.06507297 34.08700261 32.10452316 21.7514375  33.17094903]

Weekly Temperatures:
 [[31.1384336  31.63894677 23.1951493  20.30057231 27.07746834 23.84043317]
 [20.49688785 23.46218073 31.38813967 19.08680167 22.96201776 26.7947347 ]
 [33.15284694 33.35745659 18.8108851  23.7684492  30.90289356 30.73950096]
 [22.95613832 29.97162939 21.29698085 26.76535791 19.29297512 22.90207893]
 [25.28275724 17.06507297 34.08700261 32.10452316 21.7514375  33.17094903]]

Weekly Averages:
 [26.19850058 24.03179373 28.45533873 23.86419342 27.24362375]
